Changes to fix ansible-sanity errors
CiscoDevNet/ansible-dcnm pull request #297
Opened 2024-05-22 13:35 UTC by praveenramoorthy

Changes to fix ansible-sanity errors

2024-05-22 18:53 UTC, mikewiebe commented
@praveenramoorthy Looks like there are some github actions failures

2024-05-24 17:29 UTC, allenrobel requested changes
Hi Praveen,

I guess this looks good to me (and thank you for doing this work!).  It would be nice if you could add more details in the PR about why the changes were needed.  Yes, they "fix" something, but what exactly was broken?  Were all changes needed to fix the breakage, or are some changes enhancements or related to other things we've been meaning to change and decided to add them to this PR?

Also it would be good if there were a summary of changes (would really help reviewers and point them to specific areas of the code that they should look more closely at).

I'm providing such a list below.  The only change I'd request before merging this PR would be to add this list (with any modifications you feel I've missed or gotten wrong) to the main PR description.

Thanks!
Allen

### Changes
1. Reduce number of Ansible versions in the matrix
2. Wrap try-except block around third-party import
3. Remove unused imports from many files in ``modules`` and ``module_utils``
4. Update ``DOCUMENTATION`` section of modules to include ``default: []`` where needed.
5. Add ``tests/sanity/ignore-2.15.txt`` and ``ignore-2.16.txt``
6. Quote python versions in main.yaml
7. Remove two "Create ansible.cfg" tasks from main.yaml
8. Remove Python 3.12 from the matrix
9. Remove Ansible 2.14.7 from the matrix
10. Upgrade coverage from v5.4.1 to v7.3.4

2024-05-24 21:10 UTC, allenrobel approved these changes

2024-06-11 14:00 UTC, mikewiebe approved these changes

2024-06-11 14:00 UTC, merged